package mainlibrary;

import liblogger.LibLogger;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bikash
 */
public class UserViewBook extends javax.swing.JFrame {
    
    private static final String NOT_USED = "Not Issued";
    private static final String ISSUED = "Issued";
    
    
    public UserViewBook() throws SQLException {
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

        initComponents();
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        try (Connection con = DB.getConnection()) {
            try (PreparedStatement ps = con.prepareStatement("select Books.BookID, Books.BookName,Books.Genre,Books.Author,Books.Publisher, Books.Row,Books.Shelf, IssuedBook.UserID from Books left outer join IssuedBook on Books.BookID= IssuedBook.BookID;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
                try(ResultSet rs = ps.executeQuery()) {
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int colnum = rsmd.getColumnCount();

                    String row[];
                    row = new String[colnum];
                    while (rs.next()) {
                        for (int i = 1; i <= colnum; i++) {
                            if (i == colnum) {
                                if (rs.getString(i) == null) {
                                    row[i - 1] = NOT_USED;
                                } else {
                                    row[i - 1] = ISSUED;
                                }
                            } else {
                                row[i - 1] = rs.getString(i);
                            }
                        }
                        model.addRow(row);
                    }
                } catch (Exception e) {
                    LibLogger.logMessage(e.toString());
                }
            } catch (Exception e) {
                LibLogger.logMessage(e.toString());
            }

        } catch (Exception e) {
            LibLogger.logMessage(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NameRadio = new javax.swing.JRadioButton();
        AuthorRadio = new javax.swing.JRadioButton();
        ALL = new javax.swing.JRadioButton();
        NotIssued = new javax.swing.JRadioButton();
        SearchField = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        ShowALL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Book ID", "Name", "Genre", "Author", "Publisher", "Shelf", "row", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false,  false,false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Books");

        jButton1.setText("Close");
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));

        NameRadio.setText("Name");
        NameRadio.addActionListener(evt -> NameRadioActionPerformed(evt));

        AuthorRadio.setText("Author");
        AuthorRadio.addActionListener(evt -> AuthorRadioActionPerformed(evt));

        ALL.setText("ALL");
        ALL.addActionListener(evt -> ALLActionPerformed(evt));

        NotIssued.setText("NOT ISSUED");
        NotIssued.addActionListener(evt -> NotIssuedActionPerformed(evt));

        Search.setText("search");
        Search.addActionListener(evt -> SearchActionPerformed(evt));

        ShowALL.setText("Show All");
        ShowALL.addActionListener(evt -> ShowALLActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(698, 698, 698)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(NameRadio)
                        .addGap(30, 30, 30)
                        .addComponent(AuthorRadio)
                        .addGap(308, 308, 308)
                        .addComponent(ALL)
                        .addGap(40, 40, 40)
                        .addComponent(NotIssued))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(725, 725, 725)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ShowALL)
                .addGap(122, 122, 122)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Search)
                .addGap(288, 288, 288))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameRadio)
                    .addComponent(AuthorRadio)
                    .addComponent(ALL)
                    .addComponent(NotIssued))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search)
                    .addComponent(ShowALL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unused")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("unused")
    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        if (SearchField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(UserViewBook.this, "search Filed is Empty", "search Error!", JOptionPane.ERROR_MESSAGE);
        }

        if (!ALL.isSelected()) {
            if (!NotIssued.isSelected()) {
                ALL.setEnabled(true);
            }
        }

        int flag = 0;
        if (ALL.isSelected()) {
            flag = 0;
        }
        if (NotIssued.isSelected()) {
            flag = 1;
        }
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(model.getRowCount() - 1);
        }
        if (NameRadio.isSelected()) {
            String search = "%" + SearchField.getText() + "%";
            try (Connection con = DB.getConnection()) {
                try (PreparedStatement ps = con.prepareStatement("select A.BookID, A.BookName,A.Genre,A.Author,A.Publisher, A.row,A.Shelf, IssuedBook.UserID from (select * from Books where BookName like ?) as A left outer join IssuedBook on A.BookID= IssuedBook.BookID", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
                    ps.setString(1, search);
                    try (ResultSet rs = ps.executeQuery()) {
                        ResultSetMetaData rsmd = rs.getMetaData();
                        int colnum = rsmd.getColumnCount();
                        String[] row;
                        row = new String[colnum];
                        while (rs.next()) {
                            for (int i = 1; i <= colnum; i++) {
                                if (i == colnum) {
                                    if (rs.getString(i) == null) {
                                        row[i - 1] = NOT_USED;
                                        model.addRow(row);
                                    } else {
                                        if (flag == 1) {
                                            continue;
                                        }
                                        row[i - 1] = ISSUED;
                                        model.addRow(row);
                                    }
                                } else {
                                    row[i - 1] = rs.getString(i);
                                }
                            }
                        }
                        int rowcount = model.getRowCount();
                        if (rowcount == 0) {
                            String noRow[];
                            noRow = new String[7];
                            noRow[3] = "NO";
                            noRow[4] = "RESULT";
                            noRow[0] = "";
                            noRow[1] = "";
                            noRow[2] = "";
                            noRow[5] = "";
                            noRow[6] = "";
                            model.addRow(noRow);
                        }
                    } catch (Exception e) {
                        LibLogger.logMessage(e.toString());
                    }
                } catch (Exception e) {
                    LibLogger.logMessage(e.toString());
                }
            } catch (Exception e) {
                LibLogger.logMessage(e.toString());
            }
        } else if (AuthorRadio.isSelected()) {
            String search = "%" + SearchField.getText() + "%";
            try (Connection con = DB.getConnection()) {
                try (PreparedStatement ps = con.prepareStatement("select A.BookID, A.BookName,A.Genre,A.Author,A.Publisher, A.row,A.Shelf, IssuedBook.UserID from (select * from Books where Author like ?) as A left outer join IssuedBook on A.BookID= IssuedBook.BookID", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
                    ps.setString(1, search);
                    try (ResultSet rs = ps.executeQuery()) {
                        ResultSetMetaData rsmd = rs.getMetaData();
                        int colnum = rsmd.getColumnCount();
                        String row[];
                        row = new String[colnum];
                        while (rs.next()) {
                            for (int i = 1; i <= colnum; i++) {
                                if (i == colnum) {
                                    if (rs.getString(i) == null) {
                                        row[i - 1] = NOT_USED;
                                        model.addRow(row);
                                    } else {
                                        if (flag == 1) {
                                            continue;
                                        }
                                        row[i - 1] = ISSUED;
                                        model.addRow(row);
                                    }
                                } else {
                                    row[i - 1] = rs.getString(i);
                                }
                            }
                        }
                        int rowcount = model.getRowCount();
                        if (rowcount == 0) {
                            String[] noRow;
                            noRow = new String[7];
                            noRow[3] = "NO";
                            noRow[4] = "RESULT";
                            noRow[0] = "";
                            noRow[1] = "";
                            noRow[2] = "";
                            noRow[5] = "";
                            noRow[6] = "";
                            model.addRow(noRow);
                        }
                    } catch (Exception e) {
                        LibLogger.logMessage(e.toString());
                    }
                } catch (Exception e) {
                    LibLogger.logMessage(e.toString());
                }
            } catch (Exception e) {
                LibLogger.logMessage(e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(UserViewBook.this, "Select Name or Author", "No Selection!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SearchActionPerformed

    @SuppressWarnings("unused")
    private void AuthorRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorRadioActionPerformed
        NameRadio.setSelected(false);
    }//GEN-LAST:event_AuthorRadioActionPerformed

    @SuppressWarnings("unused")
    private void NameRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameRadioActionPerformed
        AuthorRadio.setSelected(false);
    }//GEN-LAST:event_NameRadioActionPerformed

    @SuppressWarnings("unused")
    private void ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALLActionPerformed
        NotIssued.setSelected(false);
    }//GEN-LAST:event_ALLActionPerformed

    @SuppressWarnings("unused")
    private void NotIssuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotIssuedActionPerformed
        ALL.setSelected(false);
    }//GEN-LAST:event_NotIssuedActionPerformed

    @SuppressWarnings("unused")
    private void ShowALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowALLActionPerformed
        AuthorRadio.setSelected(false);
        NameRadio.setSelected(false);
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(model.getRowCount() - 1);
        }

        if (!ALL.isSelected() && !NotIssued.isSelected()) {
            ALL.setSelected(true);
        }

        int flag = 0;
        if (ALL.isSelected()) {
            flag = 0;
        }
        if (NotIssued.isSelected()) {
            flag = 1;
        }

        try (Connection con = DB.getConnection()) {
            try (PreparedStatement ps = con.prepareStatement("select Books.BookID, Books.BookName,Books.Genre,Books.Author,Books.Publisher, Books.row,Books.Shelf, IssuedBook.UserID from Books left outer join IssuedBook on Books.BookID= IssuedBook.BookID;", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
                try (ResultSet rs = ps.executeQuery()) {
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int colnum = rsmd.getColumnCount();
                    String[] row;
                    row = new String[colnum];
                    while (rs.next()) {
                        for (int i = 1; i <= colnum; i++) {
                            if (i == colnum) {
                                if (rs.getString(i) == null) {
                                    row[i - 1] = NOT_USED;
                                    model.addRow(row);
                                } else {
                                    if (flag == 1) {
                                        continue;
                                    }
                                    row[i - 1] = ISSUED;
                                    model.addRow(row);
                                }
                            } else {
                                row[i - 1] = rs.getString(i);
                            }
                        }
                    }
                } catch (Exception e) {
                    LibLogger.logMessage(e.toString());
                }
            } catch (Exception e) {
                LibLogger.logMessage(e.toString());
            }
        } catch (Exception e) {
            LibLogger.logMessage(e.toString());
        }
    }//GEN-LAST:event_ShowALLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new UserViewBook().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(UserViewBook.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ALL;
    private javax.swing.JRadioButton AuthorRadio;
    private javax.swing.JRadioButton NameRadio;
    private javax.swing.JRadioButton NotIssued;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchField;
    private javax.swing.JButton ShowALL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
